services:
  php-server:
    image: php:8.2-apache
    ports:
      - "8000:80"
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html
      - ./src/php:/var/www/html/php
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
